tec = input('Digte algo: ')
print(type(tec))
print('É um número?',tec.isnumeric())
print('São letras?',tec.isalpha())
print('Esta em minúsculas?',tec.islower())
print('Esta em maiúsculas?',tec.isupper())
